### ISSUE TITLE
Optimization improvement

### ISSUE THREAD

**Issue by makeitvsolo** [Breadp4ck/oop_labs#1]
you can use `slice` instead of `vec` and not allocate memory in the heap.

https://github.com/Breadp4ck/oop_labs/blob/07b949cfff9ffcfba93c3a550f2e5caed86ba043/l1/src/main.rs#L64C13-L64C20

**Comment by Breadp4ck** [comment]
> you can use `slice` instead of `vec` and not allocate memory in the heap.
> 
> https://github.com/Breadp4ck/oop_labs/blob/07b949cfff9ffcfba93c3a550f2e5caed86ba043/l1/src/main.rs#L64C13-L64C20

Thanks for noticing!
